services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USER=guest
  #     - RABBITMQ_PASSWORD=guest
  #   depends_on:
  #     - rabbitmq
  #     - ollama
  #   networks:
  #     - crm-network
    
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"  # RabbitMQ default port
  #     - "15672:15672"  # RabbitMQ management interface
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   networks:
  #     - crm-network

  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - "11434:11434"
  #   networks:
  #     - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local 
